# this is a node build
language: node_js

# cache node modules
cache:
  directories:
    - "node_modules"

# install dependencies
install:
  - npm install --silent

# the jobs for building and deplyoing docs and demo
jobs:
  include:
    - stage: build docs and demo
      script: npm run build:docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist/docs
        target_branch: docs
        on:
          repo: ngx-material-keyboard/core
          branch: master
    - # stage name not required, will continue to use `build docs and demo`
      script: npm run build:demo
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist/demo
        target_branch: demo
        on:
          repo: ngx-material-keyboard/core
          branch: master